-- MySQL Script generated by MySQL Workbench
-- Sat Dec  7 16:46:30 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`blog_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`blog_users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`blog_users` (
  `user_id` VARCHAR(16) NOT NULL COMMENT '用户ID',
  `user_password` VARCHAR(16) CHARACTER SET 'utf8' NOT NULL COMMENT '用户密码',
  `user_email` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL COMMENT '用户邮箱',
  `user_profile_photo` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL COMMENT '用户头像',
  `user_registration_time` DATETIME NULL DEFAULT NULL COMMENT '注册时间',
  `user_birthday` DATE NULL DEFAULT NULL COMMENT '用户生日',
  `user_age` TINYINT(4) NULL DEFAULT NULL COMMENT '用户年龄',
  `user_telephone_number` INT(11) NULL DEFAULT NULL COMMENT '用户手机号',
  `user_sex` VARCHAR(3) NULL DEFAULT '未公开' COMMENT '用户性别',
  `user_description` LONGTEXT CHARACTER SET 'utf8' NULL COMMENT '用户简介',
  `user_allowArticle` TINYINT NOT NULL DEFAULT 0 COMMENT '用户是否允许发布文章',
  `user_isBanned` TINYINT NOT NULL DEFAULT 0 COMMENT '用户是否被封禁',
  PRIMARY KEY USING BTREE (`user_id`),
  INDEX `user_email` USING BTREE (`user_email`) VISIBLE,
  INDEX `user_telephone_number` USING BTREE (`user_telephone_number`) VISIBLE,
  UNIQUE INDEX `user_email_UNIQUE` (`user_email` ASC) VISIBLE,
  UNIQUE INDEX `user_telephone_number_UNIQUE` (`user_telephone_number` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = Dynamic;


-- -----------------------------------------------------
-- Table `mydb`.`blog_articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`blog_articles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`blog_articles` (
  `article_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '博文ID',
  `user_id` VARCHAR(16) NOT NULL COMMENT '发表用户ID',
  `article_title` TEXT CHARACTER SET 'utf8' NOT NULL COMMENT '博文标题',
  `article_content` LONGTEXT CHARACTER SET 'utf8' NOT NULL COMMENT '博文内容',
  `article_views` BIGINT(20) NOT NULL COMMENT '浏览量',
  `article_comment_count` BIGINT(20) NOT NULL COMMENT '评论总数',
  `article_like_count` BIGINT(20) NOT NULL COMMENT '点赞/踩数量算术和',
  `article_date` DATETIME NOT NULL COMMENT '发表时间',
  `article_isPinned` TINYINT NOT NULL DEFAULT 0 COMMENT '是否置顶',
  PRIMARY KEY USING BTREE (`article_id`),
  INDEX `user_id` USING BTREE (`user_id`) VISIBLE,
  CONSTRAINT `zj_articles_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`blog_users` (`user_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = Dynamic;


-- -----------------------------------------------------
-- Table `mydb`.`blog_messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`blog_messages` ;

CREATE TABLE IF NOT EXISTS `mydb`.`blog_messages` (
  `message_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '留言ID',
  `user_id` VARCHAR(16) NOT NULL COMMENT '发表用户ID',
  `message_like_count` BIGINT(20) NOT NULL COMMENT '点赞/踩数量算术和',
  `message_date` DATETIME NULL DEFAULT NULL COMMENT '留言日期',
  `message_content` TEXT CHARACTER SET 'utf8' NOT NULL COMMENT '留言内容',
  `parent_message_id` BIGINT(20) NULL DEFAULT NULL COMMENT '父留言ID',
  `message_isPinned` TINYINT NOT NULL DEFAULT 0 COMMENT '留言是否置顶',
  PRIMARY KEY USING BTREE (`message_id`),
  INDEX `message_date` USING BTREE (`message_date`) VISIBLE,
  INDEX `parent_message_id` USING BTREE (`parent_message_id`) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_blog_messages_blog_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`blog_users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = Dynamic;


-- -----------------------------------------------------
-- Table `mydb`.`blog_labels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`blog_labels` ;

CREATE TABLE IF NOT EXISTS `mydb`.`blog_labels` (
  `label_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '标签ID',
  `label_name` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL COMMENT '标签名称',
  `label_description` TEXT CHARACTER SET 'utf8' NOT NULL COMMENT '标签描述',
  PRIMARY KEY USING BTREE (`label_id`),
  INDEX `label_name` USING BTREE (`label_name`) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = Dynamic;


-- -----------------------------------------------------
-- Table `mydb`.`blog_set_article_label`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`blog_set_article_label` ;

CREATE TABLE IF NOT EXISTS `mydb`.`blog_set_article_label` (
  `set_label_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '设置分类ID',
  `label_id` BIGINT(20) NOT NULL COMMENT '分类ID',
  `article_id` BIGINT(20) NOT NULL COMMENT '文章ID',
  PRIMARY KEY USING BTREE (`set_label_id`),
  INDEX `label_id` (`label_id` ASC) VISIBLE,
  INDEX `article_id` (`article_id` ASC) VISIBLE,
  CONSTRAINT `fk_blog_set_artitle_label_blog_labels1`
    FOREIGN KEY (`label_id`)
    REFERENCES `mydb`.`blog_labels` (`label_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_blog_set_artitle_label_blog_articles1`
    FOREIGN KEY (`article_id`)
    REFERENCES `mydb`.`blog_articles` (`article_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = Dynamic;


-- -----------------------------------------------------
-- Table `mydb`.`blog_collection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`blog_collection` ;

CREATE TABLE IF NOT EXISTS `mydb`.`blog_collection` (
  `collection_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '收藏夹ID',
  `user_id` VARCHAR(16) NOT NULL COMMENT '所属用户ID',
  `collection_name` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL COMMENT '收藏夹名称',
  `collection_description` TEXT CHARACTER SET 'utf8' NOT NULL COMMENT '收藏夹描述',
  PRIMARY KEY USING BTREE (`collection_id`),
  INDEX `collection_name` USING BTREE (`collection_name`) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_blog_collection_blog_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`blog_users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = Dynamic;


-- -----------------------------------------------------
-- Table `mydb`.`blog_set_article_collection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`blog_set_article_collection` ;

CREATE TABLE IF NOT EXISTS `mydb`.`blog_set_article_collection` (
  `set_collection_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '设置收藏夹ID',
  `collection_id` BIGINT(20) NOT NULL COMMENT '收藏夹ID',
  `article_id` BIGINT(20) NOT NULL COMMENT '文章ID',
  PRIMARY KEY USING BTREE (`set_collection_id`),
  INDEX `article_id` (`article_id` ASC) VISIBLE,
  INDEX `collection_id` (`collection_id` ASC) VISIBLE,
  CONSTRAINT `fk_blog_set_artitle_collection_blog_articles1`
    FOREIGN KEY (`article_id`)
    REFERENCES `mydb`.`blog_articles` (`article_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_blog_set_artitle_collection_blog_collection1`
    FOREIGN KEY (`collection_id`)
    REFERENCES `mydb`.`blog_collection` (`collection_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = Dynamic;


-- -----------------------------------------------------
-- Table `mydb`.`blog_user_subscribe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`blog_user_subscribe` ;

CREATE TABLE IF NOT EXISTS `mydb`.`blog_user_subscribe` (
  `subscribe_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '标识ID',
  `user_id` VARCHAR(16) NOT NULL COMMENT '用户ID',
  `user_subscribe_id` VARCHAR(16) NOT NULL COMMENT '被关注者ID',
  PRIMARY KEY USING BTREE (`subscribe_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `user_subscribe_id` (`user_subscribe_id` ASC) VISIBLE,
  CONSTRAINT `fk_blog_user_subscribe_blog_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`blog_users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_blog_user_subscribe_blog_users2`
    FOREIGN KEY (`user_subscribe_id`)
    REFERENCES `mydb`.`blog_users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = Dynamic;


-- -----------------------------------------------------
-- Table `mydb`.`blog_comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`blog_comments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`blog_comments` (
  `comment_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '评论ID',
  `user_id` VARCHAR(16) NOT NULL COMMENT '发表用户ID',
  `article_id` BIGINT(20) NOT NULL COMMENT '评论博文ID',
  `comment_like_count` BIGINT(20) NOT NULL COMMENT '点赞数',
  `comment_date` DATETIME NULL DEFAULT NULL COMMENT '评论日期',
  `comment_content` TEXT CHARACTER SET 'utf8' NOT NULL COMMENT '评论内容',
  `parent_comment_id` BIGINT(20) NULL DEFAULT NULL COMMENT '父评论ID',
  `comment_isPinned` TINYINT NOT NULL DEFAULT 0 COMMENT '评论是否置顶',
  PRIMARY KEY USING BTREE (`comment_id`),
  INDEX `comment_date` (`comment_date` ASC) INVISIBLE,
  INDEX `parent_comment_id` USING BTREE (`parent_comment_id`) VISIBLE,
  INDEX `article_id` (`article_id` ASC) VISIBLE,
  INDEX `users_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_blog_comments_blog_articles1`
    FOREIGN KEY (`article_id`)
    REFERENCES `mydb`.`blog_articles` (`article_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_blog_comments_blog_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`blog_users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = Dynamic;


-- -----------------------------------------------------
-- Table `mydb`.`blog_comment_report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`blog_comment_report` ;

CREATE TABLE IF NOT EXISTS `mydb`.`blog_comment_report` (
  `comment_report_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '举报信息ID',
  `comment_id` BIGINT(20) NOT NULL COMMENT '举报评论ID',
  `comment_description` TEXT NOT NULL COMMENT '举报描述',
  PRIMARY KEY (`comment_report_id`),
  INDEX `comment_id` (`comment_id` ASC) VISIBLE,
  CONSTRAINT `fk_blog_comment_report_blog_comments1`
    FOREIGN KEY (`comment_id`)
    REFERENCES `mydb`.`blog_comments` (`comment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`blog_message_report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`blog_message_report` ;

CREATE TABLE IF NOT EXISTS `mydb`.`blog_message_report` (
  `message_report_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '举报信息ID',
  `message_id` BIGINT(20) NOT NULL COMMENT '举报留言ID',
  `message_description` TEXT NOT NULL COMMENT '举报描述',
  PRIMARY KEY (`message_report_id`),
  INDEX `message_id` (`message_id` ASC) VISIBLE,
  CONSTRAINT `fk_blog_message_report_blog_messages1`
    FOREIGN KEY (`message_id`)
    REFERENCES `mydb`.`blog_messages` (`message_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`blog_admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`blog_admin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`blog_admin` (
  `admin_id` INT NOT NULL AUTO_INCREMENT COMMENT '管理员编号',
  `user_id` VARCHAR(16) NOT NULL COMMENT '管理员对应用户id',
  PRIMARY KEY (`admin_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_blog_admin_blog_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`blog_users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`blog_admin_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`blog_admin_log` ;

CREATE TABLE IF NOT EXISTS `mydb`.`blog_admin_log` (
  `log_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '操作ID',
  `log_time` DATETIME NOT NULL COMMENT '操作时间',
  `log_type` VARCHAR(20) NOT NULL COMMENT '操作类型',
  `log_tableName` VARCHAR(30) NOT NULL COMMENT '表名',
  `log_description` TEXT NOT NULL COMMENT '操作事务描述',
  `admin_id` INT NOT NULL,
  PRIMARY KEY (`log_id`),
  INDEX `log_time` (`log_time` ASC) VISIBLE,
  INDEX `log_type` (`log_type` ASC) VISIBLE,
  INDEX `admin_id` (`admin_id` ASC) VISIBLE,
  CONSTRAINT `fk_blog_admin_log_blog_admin1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `mydb`.`blog_admin` (`admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`blog_like_article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`blog_like_article` ;

CREATE TABLE IF NOT EXISTS `mydb`.`blog_like_article` (
  `like_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '点赞关系编号',
  `user_id` VARCHAR(16) NOT NULL COMMENT '点赞用户id',
  `article_id` BIGINT(20) NOT NULL COMMENT '点赞文章id',
  `like_type` TINYINT NOT NULL COMMENT 'true为赞，false为踩',
  PRIMARY KEY (`like_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `article_id` (`article_id` ASC) VISIBLE,
  CONSTRAINT `fk_blog_like_article_blog_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`blog_users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_blog_like_article_blog_articles1`
    FOREIGN KEY (`article_id`)
    REFERENCES `mydb`.`blog_articles` (`article_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`blog_like_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`blog_like_comment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`blog_like_comment` (
  `like_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '点赞关系编号',
  `user_id` VARCHAR(16) NOT NULL COMMENT '点赞用户id',
  `comment_id` BIGINT(20) NOT NULL COMMENT '评论id',
  `like_type` TINYINT NOT NULL COMMENT 'true为赞，false为踩',
  PRIMARY KEY (`like_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `comment_id` (`comment_id` ASC) VISIBLE,
  CONSTRAINT `fk_blog_like_article_blog_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`blog_users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_blog_like_comment_blog_comments1`
    FOREIGN KEY (`comment_id`)
    REFERENCES `mydb`.`blog_comments` (`comment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`blog_like_message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`blog_like_message` ;

CREATE TABLE IF NOT EXISTS `mydb`.`blog_like_message` (
  `like_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '点赞关系编号',
  `user_id` VARCHAR(16) NOT NULL COMMENT '点赞用户id',
  `message_id` BIGINT(20) NOT NULL,
  `like_type` TINYINT NOT NULL COMMENT 'true为赞，false为踩',
  PRIMARY KEY (`like_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `message_id` (`message_id` ASC) VISIBLE,
  CONSTRAINT `fk_blog_like_article_blog_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`blog_users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_blog_like_message_blog_messages1`
    FOREIGN KEY (`message_id`)
    REFERENCES `mydb`.`blog_messages` (`message_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
